### ISSUE TITLE
what should I do to deploy the contract

### ISSUE THREAD

**Issue by pipBug** [cleanunicorn/theo#10]
I successfully started the local ethereum node using the 'ganache-cli -d' command.
![image](https://user-images.githubusercontent.com/13911593/63915562-f0fc8000-ca68-11e9-87c1-50a6d140a55c.png)
next step: Deploy the vulnerable contract (happens in a different window) How do I do it?

**Comment by josu22** [comment]
You can do it with https://github.com/kvhnuke/etherwallet/releases.

http://remix.ethereum.org for use IDE to get the bytecode from the contract.

**Comment by pipBug** [comment]
Ok, thank you very much.
